### ISSUE TITLE
Doesn't work with scenes not named "Scene"

### ISSUE THREAD

**Issue by Koopa1018** [AsgerSuhr/UDIM_baking#6]
When clicking the "Bake to UDIMs" button, I get the following error:
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UDIM_baker.py", line 235, in execute
    bake_udim(context)
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UDIM_baker.py", line 186, in bake_udim
    check_multires = bpy.data.scenes['Scene'].render.use_bake_multires
KeyError: 'bpy_prop_collection[key]: key "Scene" not found'

location: <unknown location>:-1
```
I make a habit of renaming my .blend files' scenes once I have multiple. Judging by the error, this addon doesn't seem to like that.

**Comment by AsgerSuhr** [comment]
should be fixed now
